id = "ftl-extension"
name = "FTL Language Support"
description = "Provides syntax highlighting and other features for Fluent (.ftl) files."
version = "0.1.0"
schema_version = 1
authors = ["taimast <charlskenno@gmail.com>"]
repository = "https://github.com/taimast/zed-ftl-extension"

# Подключение вашего Tree-sitter парсера
[grammars.ftl]
repository = "https://github.com/taimast/tree-sitter-ftl"
commit = "f9cf844ded07fe8cc8aa3fbe84e6498b8e7cf76f"

# Подключение вашего языкового сервера (если есть)
#[language_servers.ftl]
#name = "FTL Language Server"
#language = "Fluent"
